### ISSUE TITLE
Details page: return to top

### ISSUE THREAD

**Issue by MennaRempt** [ErwinKomen/RU-passim#604]
For all details pages, add a button "return to top" at the bottom of the page to bring users back to the top of the page when clicked.

**Comment by ErwinKomen** [comment]
### Implementation
1. Added code in CSS to facilitate classes for the button and the scroll-back-to-top (see below)
3. Added a button div in `basic_details.html`:
``` html
...
<div class="scrolltop-allow">
   ...
   <div class="scrolltop-container">
      <a class="" href="#top" title="Scroll back to top">
        <span class="glyphicon glyphicon-triangle-top"></span>
      </a>
    </div>
</div>
```

The CSS:
``` css
/* Scroll to top button facilitation */
.scrolltop-allow {
    position: relative;
}
.scrolltop-container {
    position: absolute;
    top: 0;
    right: 25px;
    height: 100%;
}
.scrolltop-container:before {
    content: '';
    display: block;
    height: 100vh;
    pointer-events: none;
}
.scrolltop-container a {
    position: sticky;
    top: 92vh;
    cursor: pointer;
    color: chocolate;
    font-size: 40px;
}
```
